env: "dev"

grpc_server:
  address: "0.0.0.0"
  port: 50052

database:
  username: "postgres"
  password: "admin"
  host: "auth-db"
  port: "5433"
  db_name: "authservice"
  migrations_path: "./migrations"

jwt:
  secret: "my-secret"
  access_expires_at: "1m"
  refresh_expires_at: "5m"

user_service:
  address: "user-service"
  port: 50051
